### ISSUE TITLE
Relative path for openapi spec in gherkin background fails

### ISSUE THREAD

**Issue by jagadeeswarvenkatasubbu** [specmatic/specmatic#815] opened 2023-11-15 11:33 UTC
**Description**
Relative path for openapi spec in gherkin background fails

**Steps to reproduce**
1. Create a `.spec` file like below
```
Feature: Some important feature

  Background:
    Given openapi api-spec-of-some-important-feature.yaml

Scenario Outline: Important scenario
    When POST /important/path
    And request-body { data: (string) }
    Then status 201
    Examples:
      | data |
      | important data |

``` 
3. Run the contract tests with this spec.
4. It fails, wth below error
```
io.swagger.v3.parser.exception.ReadContentException: Unable to read location `/Users/XXX/apps/api-spec-of-some-important-feature.yaml`
	at io.swagger.v3.parser.OpenAPIV3Parser.readContentFromLocation(OpenAPIV3Parser.java:308)
	at io.swagger.v3.parser.OpenAPIV3Parser.readLocation(OpenAPIV3Parser.java:95)
	at io.swagger.v3.parser.OpenAPIV3Parser.read(OpenAPIV3Parser.java:124)
``` 
I tried with `./api-spec-of-some-important-feature.yaml` as well, it throws the same error with `/Users/XXX/apps/./api-spec-of-some-important-feature.yaml`

Actual location of the file - `/Users/XXX/apps/<project-folder>/api-spec-of-some-important-feature.yaml`
**Expected behavior**
It is able to read the spec and process the scenarios, like how it behaves for absolute path

**System Information:**
 - OS & version: MacOS 14.1
 - Browser & version: N/A
 - Specmatic version: 0.81.0
 - JDK version: 17

**Additional context**
Upon some debugging, the likely root cause could be in `in`.specmatic.conversions.OpenApiSpecification, line # 48

```
fun fromFile(openApiFilePath: String, relativeTo: String = ""): OpenApiSpecification {
            val openApiFile = File(openApiFilePath).let { openApiFile ->
                if (openApiFile.isAbsolute) {
                    openApiFile
                } else {
                    File(relativeTo).canonicalFile.parentFile.resolve(openApiFile) #line - 48
                }
            }

            return fromFile(openApiFile.canonicalPath)
        }
````
File(relativeTo).canonicalFile.parentFile.resolve(openApiFile). This code has `.canonicalFile` and `.parentFile`, this takes the current path to one step above the desired path.

**Comment by harikrishnan83** [comment] 2023-11-27 10:07
@jagadeeswarvenkatasubbu thanks for reaching out. Apologies for the delay in response. We will investigate this.

Meanwhile, we recently introduced another mechanism to externalise test data without Gherkin by having the tests in JSON files (similar to how have stub data). Here is the [documentation](https://specmatic.in/documentation/contract_tests.html#externalized-test-data). We would encourage moving to this as an approach as we are trying to minimise our dependency on Gherkin.

That said, since you have already seem to have identified the root cause for the Gherkin spec related issue, we will be happy accept a Pull Request for the same.

cc @joelrosario

**Comment by joelrosario** [comment] 2024-02-12 09:28
Hi @jagadeeswarvenkatasubbu, apologies for the delay.

I was not able to reproduce the problem.

Here are the steps I followed to try to reproduce it.

Experiment 1:
1. I created an OpenAPI file named `products.yaml` (see below).
2. I created a spec file named `wrapper.spec` (see below) which wrapped `products.yaml`.
3. Both files are in the same directry.
4. I ran the command `java -jar specmatic.jar test products.yaml`.
5. Specmatic ran the contract tests, and did not show any error with respect to `products.yaml`.

Experiment 2:
7. I created a file named specmatic.json (see below)
8. I ran `java -jar specmatic.jar test`
9. Specmatic was able to find `products.yaml`

Experiment 3:
I attempted a similar experiment with Specmatic's Java helpers, using specmatic.json, but in this too I was unable to replicate the problem.

**products.yaml**
```yaml
openapi: 3.0.0
info:
  title: Product API
  version: 1.0.0
paths:
  /products:
    post:
      summary: Create a new product record
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                description:
                  type: string
      responses:
        '201':
          description: Product created successfully
        '400':
          description: Invalid request payload
        '500':
          description: Internal server error
```

**wrapper.spec**
```gherkin
Feature: Some important feature

  Background:
    Given openapi products.yaml

  Scenario Outline: Important scenario
    When POST /products
    And request-body { data: "(string)" }
    Then status 201
    Examples:
      | name | price | description |
      | Book | 10    | Textbook    |
```

**specmatic.json**
```json
{
  "sources": [
    {
      "provider": "filesystem",
      "test": [
        "wrapper.spec"
      ]
    }
  ]
}
```

Can you provide the following details, to help us replicate the issue:
1. Sample files (OpenAPI file matching the above Gherkin wrapper, specmatic.json file if any)
3. The paths of the wrapper and OpenAPI files (e.g. are they in the same directory)
4. The approach used to run the contract tests (e.g. if you used the command, please share the command)
5. If you used the command, the directory the terminal was in when you ran the test.

**Comment by joelrosario** [comment] 2024-02-20 06:18
@jagadeeswarvenkatasubbu closing this issue for now. But please reopen it when you are able to provide the details I've requested in my previous comment. Thanks!

**Closed as completed by joelrosario** 2024-02-20 06:18 UTC
Labels: question
