### ISSUE TITLE
File folder path and @wip/@ignore provision for spec files

### ISSUE THREAD

**Issue by nidhi-tomar93** [specmatic/specmatic#271] opened 2021-06-09 11:17 UTC
**Is your feature request related to a problem? Please describe.**
1. @wip/@ignore tags should be provided to ignore the set of scenarios in Specmatic 
2. In specmatic.json, we have "test" and "stubs", where we define the filePath. In the case of 1xxx API contracts, JSON will become huge. 

**Describe the solution you'd like**
1. @wip/@ignore tags should be supported to comment out the scenarios 
2. Instead of mentioning the path for all 1xxx APIs, better to mention the folder path in "test" and "stub". 
eg:
/** Current structure **/
/** NOTE: Consider n = 1xxx **/
"test": 
[
  "/projectName/name1/specFolder1/module1/fileName1.spec" , 
  "/projectName/name1/specFolder1/module1/fileName2.spec",
  "/projectName/name1/specFolder1/module2/fileName1.spec" 
  "/projectName/name1/specFolder1/module3/fileName1.spec" 
                                         "
                                         "
                                         "
  "/projectName/name1/specFolder1/module<n>/fileName<n>.spec" 
],
"stub":
[
  "/projectName/name2/stubFolder1/stubServiceName1.spec" 
  "/projectName/name2/stubFolder1/stubServiceName1.spec" 
                                         "
                                         "
                                         "
  "/projectName/name2/stubFolder1/stubServiceName<n>.spec" 
]

/** Suggested Solution **/
/** NOTE: Consider n = 1xxx **/
"test":
[
 "/projectName/name1/specFolder1/.."
]
"stub":
[
"/projectName/name1/stubFolder1/..."
]

**Comment by sahilaug** [comment] 2021-06-09 11:40
https://specmatic.in/documentation/Versioning.html#handling-contracts-in-progress 
Check the above documentation for use of WIP tag

**Comment by sahilaug** [comment] 2021-06-09 11:41
The second point is a duplicate of https://github.com/znsio/specmatic/issues/113

**Closed as completed** 2021-06-09 14:09 UTC
