### ISSUE TITLE
Related REQUEST and RESPONSE

### ISSUE THREAD

**Issue by GagandeepSharma060** [specmatic/specmatic#1409] opened 2024-11-02 19:46 UTC
Hi team,

Just curious if there is a way in which we can do some math over any request param and return it in the response value

FOr expample, if there is some creationTime in the request param having some value and in the response I always want to send 2 + the value of creationTIme in the request, is there any way it is possible?

**Comment by GagandeepSharma060** [comment] 2024-11-02 20:00
I see this 
<img width="1094" alt="image" src="https://github.com/user-attachments/assets/0d097778-e995-49ee-bbe7-652c43e6342b">


Can u show me the same example but not with a shell script but some js code to do the same

Will be really helpful

**Comment by pranavgawri** [comment] 2024-11-03 13:21
Hi @GagandeepSharma060 ,

Thank you for reaching out with your requirement, and I appreciate your proactive approach in referring to our documentation here: [Externalized Response Generation](https://specmatic.io/documentation/service_virtualization_tutorial.html#externalised-response-generation)

To adapt the example for JavaScript, here are the modifications you'll need to make:

## 1. Modify expectation json
You will have to modify your expectation/example json, please find the modified version below
```json
{
  "http-request": {
    "method": "GET",
    "path": "/triple/(value:number)"
  },
  "http-response": {
    "status": 200,
    "body": "10",
    "externalisedResponseCommand": "node ./response.js"
  }
}
```
> Note: Update "node ./response.js" as per your setup and file path.


## 2.  JavaScript externalized script
Following is the JavaScript equivalent for the Shell script that was shared in the [documentation](https://specmatic.io/documentation/service_virtualization_tutorial.html#externalised-response-generation)
```javascript
// Read SPECMATIC_REQUEST from the environment variable
const SPECMATIC_REQUEST = process.env.SPECMATIC_REQUEST || "";

// Extract the 19th character (index 18) from SPECMATIC_REQUEST (you can modify this as per your need)
const value = SPECMATIC_REQUEST.charAt(18);

// Convert the extracted character to a number and multiply by 3
// Use parseInt to ensure we get a numeric value; fallback to 0 if not a valid number
const numericValue = parseInt(value, 10) || 0;
const bodyValue = numericValue * 3;

// Output the JSON response
const response = {
    status: 200,
    body: bodyValue,
    "status-text": "OK",
    headers: {
        "X-Specmatic-Result": "success",
        "Content-Type": "application/json"
    }
};

console.log(JSON.stringify(response, null, 4));
```

I hope this covers your requirement. Please don’t hesitate to reach out if you have further questions.

Thanks,
Pranav

**Comment by pranavgawri** [comment] 2024-11-12 09:29
Hi @GagandeepSharma060 ,

Hope you're doing fine! I wanted to follow up to check if my previous response helped resolve your question.

I'd also like to share two more useful features that are close to your requirements:

- [Copy Values from Request to Response](https://specmatic.io/documentation/service_virtualization_tutorial.html#direct-substitution---copying-values-from-request-to-response)
- [Coordinated Response Values using Data Lookup](https://specmatic.io/documentation/service_virtualization_tutorial.html#data-lookup)

Please let me know if you need any clarification or have additional questions! If the issue is resolved, I'd appreciate if you could close this ticket.


Thanks,
Pranav

**Comment by samyakOO7** [comment] 2024-11-19 12:03
Hello @GagandeepSharma060, hope you are doing fine! Currently I guess we are good to close this issue, we are welcome to any further clarifications, please feel free to reopen if needed.

Thanks

**Closed as completed by samyakOO7** 2024-11-19 12:03 UTC
Labels: answered
