### ISSUE TITLE
Pytest not failing when specmatic test cases has failures.

### ISSUE THREAD

**Issue by barath121** [specmatic/specmatic#1304] opened 2024-09-17 05:06 UTC
**Description**
Pytest not failing when specmatic test cases has failures.

**Steps to reproduce**
1. Run specmatic test cases where test cases fail.
2. Check pytest results
3. Sample output
```
Unsuccessful Scenarios:
  "Load Error FAILED"
        Reason: Error loading example named success for GET / -> 200
           
                   >> RESPONSE.BODY.message4
           
                      The key message4 was found in the example success but was not in the specification.

Tests run: 1, Successes: 0, Failures: 1, Errors: 0

Executed at 2024-09-17T10:30:47.944808
Injecting pytest methods

 Shutting down specmatic stub server on localhost:3030, please wait ...
Stopping app server...
PASSED
```

**Expected behavior**
In case of specmatic failure pytest should throw error and exit with non zero code.

**System Information:**
 - Specmatic version: 2.0.17 (Python specmatic wrapper).

**Comment by harikrishnan83** [comment] 2024-09-18 12:05
hello @barath121 , thanks for reporting this. Based on the details you have shared, this looks like a inline example (with the name `success`) validation failure in the OpenAPI spec. We tried reproducing the issue by simulating similar scenario with the specific version of Specmatic you have mentioned here and we see a non-zero exit code (since this screenshot was taken on a Windows machine `%ERROR_LEVEL%` is the equivalent of `$?`). Please see screenshot for your reference. Anything we are missing here?

![Screenshot 2024-09-17 112631 1](https://github.com/user-attachments/assets/5a925098-753b-401a-a496-14784268986f)

**Comment by harikrishnan83** [comment] 2024-10-01 08:30
@barath121 as spoken, the issue is happening in your case because you are trying to invoke `Specmatic()` function within another function and thereby `pytest.main()` is called even before Specmatic has a chance to add the tests dynamically. So PyTest assumes there are no tests and exits with code zero. Closing this issue as agreed. Thanks. cc @StarKhan6368

**Closed as completed by harikrishnan83** 2024-10-01 08:30 UTC
