### ISSUE TITLE
Could not start stub server with requestBody as xml format. Getting the following error: getProperties(...) must not be null with 81 version of specmatic.jar and getting schema.properties must not be null error with 56 version.

### ISSUE THREAD

**Issue by Jaganudumula** [specmatic/specmatic#801] opened 2023-10-31 09:01 UTC
Could not start stub server with requestBody as xml format. Getting the following error: getProperties(...) must not be null with 81 version of specmatic.jar and getting schema.properties must not be null error with 56 version.

**Comment by harikrishnan83** [comment] 2023-10-31 09:34
hello @Jaganudumula, thanks for reporting the issue. Can you please share a sample of the OpenAPI specification you are using? That will help us understand / reproduce the issue.

**Comment by Jaganudumula** [comment] 2023-10-31 12:12
[Sample api.txt](https://github.com/znsio/specmatic/files/13216109/Sample.api.txt)
It did not accept .yaml file to upload, so I changed the extension to .txt and uploaded.

**Comment by Jaganudumula** [comment] 2023-11-08 05:06
@harikrishnan83 any solution for this issue?

**Comment by joelrosario** [comment] 2023-11-14 11:12
Hi @Jaganudumula, thanks for reporting this, we'll have a look.

However, the issue is occurring because the schema of the XML request payload does not have any properties defined. You should be able to get past this by defining them, as described in the [OpenAPI documentation here](https://swagger.io/specification/v3/).

Hope this helps.

**Comment by Jaganudumula** [comment] 2023-11-17 11:56
Hello @joelrosario, thank you for the response.
I tried by adding the properties field in request body but still getting the same error.

**Comment by jaydeepk** [comment] 2023-12-05 08:02
@Jaganudumula , apologies for the delay in responding.
Would it be possible for you to provide the updated yaml file in which you have added properties.

**Comment by joelrosario** [comment] 2024-02-11 15:26
Hi @Jaganudumula 

I was able to get this loading as a stub, after adding properties. Please try the specification below.

```xml
openapi: "3.0.3"
info:
  description: This documentation contains REST API contract details
  version: "1.0.0"
  title: REST API
  
paths:
  /xyz/api/rest/v1/book:
    post:
      tags:
        - V1
      summary: Post an entry
      description: |
        - Post an entry
      operationId: postEntry
      requestBody:
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/PostEntryXmlRequest'
            examples:
              file:
                summary: A sample message
                value: >-
                  <?xml version="1.0" encoding="UTF-8"?>
                  <Document xmlns="urn:iso:std:iso:20022:tech:xsd:camt.054.001.02">
                  –<BkToCstmrDbtCdtNtfctn>
                  - <GrpHdr>
                  <MsgId>XML990920151125223537343</MsgId>
                  <CreDtTm>2015-11-25T21:35:37Z</CreDtTm>
                  - <MsgRcpt>
                  - <Id>
                  - <OrgId>
                  - <Othr>
                  <Id>7786849266</Id>
                  - <SchmeNm>
                  <Cd>CUST</Cd>
                  </SchmeNm>
                  </Othr>
                  </OrgId>
                  </Id>
                  </MsgRcpt>
                  <AddtlInf>/DEBT/</AddtlInf>
                  </GrpHdr>
                  - <Ntfctn>
                  <Id>2015-11-25-22.35.37-SEK2121</Id>
                  <CreDtTm>2015-11-25T21:35:37Z</CreDtTm
      responses:
        '202':
          description: >-
            Accepted
          headers:
            X-Request-ID:
              schema:
                type: string
              description: ID
        '400':
          description: Invalid input for posting entry.

    parameters:
      - $ref: '#/components/parameters/X-Token'
      - $ref: '#/components/parameters/X-Request-ID'

components:
  parameters:
    X-Token:
      name: X-Token
      in: header
      required: true
      schema:
        type: string
    X-Request-ID:
      name: X-Request-ID
      in: header
      required: true
      schema:
        type: string

  schemas:
    PostEntryXmlRequest:
      title: PostEntryXmlRequest
      type: object
      xml:
        name: Document
      properties:
        id:
          type: integer
        name:
          type: string

  responses:
    Unauthorized:
      description: Unauthorized action
      
    Forbidden:
      description: The user is not allowed to access this service.
```

We have recently added a fix so that the error message reports the name of the schema intended to define an XML node, if it has no properties. The fix will be out soon.

Btw Specmatic is now at version 1.2.17, with many improvements and feature since the last time you tried it.

Closing this issue for now. But please reopen it if you have any followup questions.

**Closed as completed by joelrosario** 2024-02-11 15:26 UTC
Labels: question
